blank_issues_enabled: true
contact_links:
  - name: Start a discussion
    url: https://github.com/thomasgalliker/Superdev.Maui.Maps/discussions/new/choose
    about: We use Discussions for these reports